### ISSUE TITLE
java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.

### ISSUE THREAD

**Issue by Amab** [Amab/SWADroid#114]
``` bash
java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
at android.database.CursorWindow.nativeGetLong(Native Method)
at android.database.CursorWindow.getLong(CursorWindow.java:507)
at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
at com.android.dataframework.DataFramework.getEntityList(DataFramework.java:221)
at com.android.dataframework.DataFramework.getEntityList(DataFramework.java:195)
at es.ugr.swad.swadroid.model.DataBaseHelper.clearOldNotifications(DataBaseHelper.java:1816)
at es.ugr.swad.swadroid.modules.notifications.NotificationsSyncAdapterService.getNotifications(NotificationsSyncAdapterService.java:367)
at es.ugr.swad.swadroid.modules.notifications.NotificationsSyncAdapterService.performSync(NotificationsSyncAdapterService.java:443)
at es.ugr.swad.swadroid.modules.notifications.NotificationsSyncAdapterService.access$1(NotificationsSyncAdapterService.java:410)
at es.ugr.swad.swadroid.modules.notifications.NotificationsSyncAdapterService$SyncAdapterImpl.onPerformSync(NotificationsSyncAdapterService.java:105)
at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:261)
java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
at android.database.CursorWindow.nativeGetLong(Native Method)
at android.database.CursorWindow.getLong(CursorWindow.java:507)
at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
at com.android.dataframework.DataFramework.getEntityList(DataFramework.java:221)
at com.android.dataframework.DataFramework.getEntityList(DataFramework.java:195)
at es.ugr.swad.swadroid.model.DataBaseHelper.clearOldNotifications(DataBaseHelper.java:1816)
at es.ugr.swad.swadroid.modules.notifications.NotificationsSyncAdapterService.getNotifications(NotificationsSyncAdapterService.java:367)
at es.ugr.swad.swadroid.modules.notifications.NotificationsSyncAdapterService.performSync(NotificationsSyncAdapterService.java:443)
at es.ugr.swad.swadroid.modules.notifications.NotificationsSyncAdapterService.access$1(NotificationsSyncAdapterService.java:410)
at es.ugr.swad.swadroid.modules.notifications.NotificationsSyncAdapterService$SyncAdapterImpl.onPerformSync(NotificationsSyncAdapterService.java:105)
at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:261)

```

**Comment by satlaibtissem** [comment]
What was the solution to this problem ?!!
