### ISSUE TITLE
javax.net.ssl.SSLProtocolException: Read error: ssl=0x321a28: Failure in SSL library, usually a protocol error

### ISSUE THREAD

**Issue by Amab** [Amab/SWADroid#125]
``` bash
javax.net.ssl.SSLProtocolException: Read error: ssl=0x321a28: Failure in SSL library, usually a protocol error
at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_read(Native Method)
at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:788)
at org.apache.harmony.luni.internal.net.www.protocol.http.FixedLengthInputStream.read(FixedLengthInputStream.java:44)
at java.io.BufferedInputStream.read(BufferedInputStream.java:319)
at java.io.FilterInputStream.read(FilterInputStream.java:133)
at es.ugr.swad.swadroid.modules.downloads.FileDownloaderAsyncTask.downloadFileCustom(FileDownloaderAsyncTask.java:175)
at es.ugr.swad.swadroid.modules.downloads.FileDownloaderAsyncTask.doInBackground(FileDownloaderAsyncTask.java:289)
at es.ugr.swad.swadroid.modules.downloads.FileDownloaderAsyncTask.doInBackground(FileDownloaderAsyncTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:185)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
at java.lang.Thread.run(Thread.java:1019)
javax.net.ssl.SSLProtocolException: Read error: ssl=0x321a28: Failure in SSL library, usually a protocol error
at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_read(Native Method)
at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:788)
at org.apache.harmony.luni.internal.net.www.protocol.http.FixedLengthInputStream.read(FixedLengthInputStream.java:44)
at java.io.BufferedInputStream.read(BufferedInputStream.java:319)
at java.io.FilterInputStream.read(FilterInputStream.java:133)
at es.ugr.swad.swadroid.modules.downloads.FileDownloaderAsyncTask.downloadFileCustom(FileDownloaderAsyncTask.java:175)
at es.ugr.swad.swadroid.modules.downloads.FileDownloaderAsyncTask.doInBackground(FileDownloaderAsyncTask.java:289)
at es.ugr.swad.swadroid.modules.downloads.FileDownloaderAsyncTask.doInBackground(FileDownloaderAsyncTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:185)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
at java.lang.Thread.run(Thread.java:1019)

```

**Comment by angelapp** [comment]
Hi @Amab , could you resolve resolve this problem? I'm getting the same error "javax.net.ssl.SSLProtocolException: Read error: ssl=0x82aba270: Failure in SSL library, usually a protocol error" at this moment.
I'll appreciate whatever information you give me.

Greetings!

**Comment by Amab** [comment]
Hi @angelapp, could you post the following info, please?

- SWADroid version
- Android version
- Device model

Thanks.

**Comment by angelapp** [comment]
Hi Juan,

I'm sorry, I wrote in the wrong thread, I was referring to the general
error we get, not to a SWADroid's specific error. We are developing an
application that library and we get that log error. If you know how to
avoid that we'll be grateful.

Many thanks!

*Daniel Trujillo*
*3168722663 <3168722663>*
*daniel.trujillo@angelapp.com.co <daniel.trujillo@angelapp.com.co>*
*Angel App Team*

2016-02-09 17:11 GMT-05:00 Juan Miguel Boyero Corral <
notifications@github.com>:
