### ISSUE TITLE
java.lang.IllegalStateException: Cannot set request property after connection is made

### ISSUE THREAD

**Issue by Amab** [Amab/SWADroid#15]
java.lang.IllegalStateException: Cannot set request property after connection is made
at libcore.net.http.HttpURLConnectionImpl.setRequestProperty(HttpURLConnectionImpl.java:484)
at libcore.net.http.HttpsURLConnectionImpl.setRequestProperty(HttpsURLConnectionImpl.java:330)
at org.ksoap2.transport.HttpsServiceConnectionSE.setRequestProperty(HttpsServiceConnectionSE.java:112)
at org.ksoap2.transport.HttpsServiceConnectionSEIgnoringConnectionClose.setRequestProperty(HttpsServiceConnectionSEIgnoringConnectionClose.java:19)
at org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:146)
at org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:114)
at es.ugr.swad.swadroid.modules.Module.sendRequest(Module.java:436)
at es.ugr.swad.swadroid.modules.downloads.DirectoryTreeDownload.requestService(DirectoryTreeDownload.java:58)
at es.ugr.swad.swadroid.modules.Module$Connect.doInBackground(Module.java:525)
at es.ugr.swad.swadroid.modules.Module$Connect.doInBackground(Module.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:264)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:856)
java.lang.IllegalStateException: Cannot set request property after connection is made
at libcore.net.http.HttpURLConnectionImpl.setRequestProperty(HttpURLConnectionImpl.java:484)
at libcore.net.http.HttpsURLConnectionImpl.setRequestProperty(HttpsURLConnectionImpl.java:330)
at org.ksoap2.transport.HttpsServiceConnectionSE.setRequestProperty(HttpsServiceConnectionSE.java:112)
at org.ksoap2.transport.HttpsServiceConnectionSEIgnoringConnectionClose.setRequestProperty(HttpsServiceConnectionSEIgnoringConnectionClose.java:19)
at org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:146)
at org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:114)
at es.ugr.swad.swadroid.modules.Module.sendRequest(Module.java:436)
at es.ugr.swad.swadroid.modules.downloads.DirectoryTreeDownload.requestService(DirectoryTreeDownload.java:58)
at es.ugr.swad.swadroid.modules.Module$Connect.doInBackground(Module.java:525)
at es.ugr.swad.swadroid.modules.Module$Connect.doInBackground(Module.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:264)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:856)

**Comment by OmarHassan25** [comment]
How did you resolve this issue?

**Comment by maxiongyue585** [comment]
How did you resolve this issue?

**Comment by maxiongyue585** [comment]
How did you resolve this issue?
